
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 7
#define PANDA_SEQUENCE_VERSION 1
#define PANDA_VERSION 1007000
#define PANDA_NUMERIC_VERSION 1007000
#define PANDA_VERSION_STR "1.7.1"
#define PANDA_ABI_VERSION_STR "1.7"
#define PANDA_DISTRIBUTOR "Rocket"
#define PANDA_PACKAGE_VERSION_STR "Rocket_1.7"
#define PANDA_PACKAGE_HOST_URL "http://download.sunrise.games/runtime"

#undef  PANDA_OFFICIAL_VERSION
